// data.js
export const countriesData = [
    { country: "Japan", currency: "Yen", options: ["Won", "Yen", "Baht"] },
    { country: "USA", currency: "Dollar", options: ["Pound", "Euro", "Dollar"] },
    { country: "India", currency: "Rupee", options: ["Rupee", "Yuan", "Baht"] },
    { country: "Germany", currency: "Euro", options: ["Dollar", "Euro", "Pound"] },
    { country: "UK", currency: "Pound", options: ["Euro", "Yen", "Pound"] },
    { country: "Australia", currency: "Dollar", options: ["Yuan", "Dollar", "Euro"] },
    { country: "Canada", currency: "Dollar", options: ["Yen", "Euro", "Dollar"] },
    { country: "France", currency: "Euro", options: ["Pound", "Dollar", "Euro"] },
    { country: "Italy", currency: "Euro", options: ["Yen", "Dollar", "Euro"] },
    { country: "Spain", currency: "Euro", options: ["Pound", "Euro", "Yuan"] },
    { country: "China", currency: "Yuan", options: ["Baht", "Yuan", "Dollar"] },
    { country: "Brazil", currency: "Real", options: ["Real", "Pound", "Euro"] },
    { country: "South Korea", currency: "Won", options: ["Yen", "Won", "Rupee"] },
    { country: "Mexico", currency: "Peso", options: ["Peso", "Yen", "Dollar"] },
    { country: "Russia", currency: "Ruble", options: ["Ruble", "Euro", "Pound"] },
    { country: "South Africa", currency: "Rand", options: ["Dollar", "Euro", "Rand"] },
    { country: "Sweden", currency: "Krona", options: ["Euro", "Krona", "Yen"] },
    { country: "Norway", currency: "Krona", options: ["Krona", "Yuan", "Euro"] },
    { country: "Switzerland", currency: "Franc", options: ["Franc", "Dollar", "Yuan"] },
    { country: "Singapore", currency: "Dollar", options: ["Dollar", "Yen", "Euro"] },
    { country: "Turkey", currency: "Lira", options: ["Lira", "Yen", "Euro"] },
    { country: "Saudi Arabia", currency: "Riyal", options: ["Riyal", "Euro", "Yen"] },
    { country: "Egypt", currency: "Pound", options: ["Dollar", "Pound", "Yen"] },
    { country: "Israel", currency: "Shekel", options: ["Yen", "Shekel", "Dollar"] },
    { country: "Argentina", currency: "Peso", options: ["Peso", "Yen", "Euro"] },
    { country: "Chile", currency: "Peso", options: ["Peso", "Yuan", "Dollar"] },
    { country: "New Zealand", currency: "Dollar", options: ["Dollar", "Yen", "Baht"] },
    { country: "Thailand", currency: "Baht", options: ["Baht", "Euro", "Dollar"] },
    { country: "Malaysia", currency: "Ringgit", options: ["Yuan", "Baht", "Ringgit"] },
    { country: "Vietnam", currency: "Dong", options: ["Yen", "Dong", "Dollar"] },
    { country: "Philippines", currency: "Peso", options: ["Peso", "Yuan", "Baht"] },
    { country: "Pakistan", currency: "Rupee", options: ["Rupee", "Dollar", "Yen"] },
    { country: "Bangladesh", currency: "Taka", options: ["Dollar", "Taka", "Yuan"] },
    { country: "Nepal", currency: "Rupee", options: ["Rupee", "Yen", "Dollar"] },
    { country: "Indonesia", currency: "Rupiah", options: ["Yuan", "Rupiah", "Euro"] },
    { country: "Nigeria", currency: "Naira", options: ["Naira", "Pound", "Euro"] },
    { country: "Kenya", currency: "Shilling", options: ["Shilling", "Euro", "Pound"] },
    { country: "Greece", currency: "Euro", options: ["Pound", "Euro", "Yuan"] },
    { country: "Poland", currency: "Zloty", options: ["Euro", "Zloty", "Yen"] },
    { country: "Czech Republic", currency: "Koruna", options: ["Koruna", "Euro", "Yen"] },
    { country: "Hungary", currency: "Forint", options: ["Euro", "Forint", "Dollar"] },
    { country: "Romania", currency: "Leu", options: ["Leu", "Yuan", "Euro"] },
    { country: "Slovakia", currency: "Euro", options: ["Euro", "Yuan", "Rupee"] },
    { country: "Bulgaria", currency: "Lev", options: ["Lev", "Yen", "Euro"] },
    { country: "Croatia", currency: "Kuna", options: ["Euro", "Kuna", "Yuan"] },
    { country: "Serbia", currency: "Dinar", options: ["Yen", "Dinar", "Dollar"] },
    { country: "Montenegro", currency: "Euro", options: ["Euro", "Dollar", "Yuan"] },
    { country: "Albania", currency: "Lek", options: ["Lek", "Euro", "Dollar"] },
    { country: "Macedonia", currency: "Denar", options: ["Denar", "Euro", "Yen"] },
    { country: "Kosovo", currency: "Euro", options: ["Euro", "Dollar", "Yuan"] },
    { country: "Bosnia and Herzegovina", currency: "Convertible Mark", options: ["Convertible Mark", "Euro", "Dollar"] },
    { country: "Malta", currency: "Euro", options: ["Euro", "Pound", "Yen"] },
    { country: "Luxembourg", currency: "Euro", options: ["Euro", "Yen", "Dollar"] },
    { country: "Liechtenstein", currency: "Franc", options: ["Franc", "Euro", "Dollar"] },
    { country: "Monaco", currency: "Euro", options: ["Euro", "Dollar", "Yen"] },
    { country: "Andorra", currency: "Euro", options: ["Euro", "Yen", "Dollar"] },
  ];
  
  